import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Provider } from "./Web3Provider";
import Header from "./Header";
import { Space_Grotesk } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Web3Provider>
      <html lang="en">
        <head></head>
        <body className={grotesk.className}>
          <>
            <Header />
            {children}
          </>
        </body>
      </html>
    </Web3Provider>
  );
}
